nelmio_api_doc:
    documentation:
        info:
            title: API V3
            description: API V3 for new.aftaa.ru
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: Bearer
                    name: token
                    in: header
        paths:
            /login_check:
                post:
                    tags:
                        - Login
                    description: Login into api test@test.ru:test
                    requestBody:
                        description: Json body
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        '200':
                            description: Login successful
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                        '401':
                            description: Login failed
    areas: # to filter documented areas
        path_patterns:
            - ^/private # Accepts routes under /api except /api/doc
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
